// Code generated by "mapstructure-to-hcl2 -type SecurityGroupFilterOptions,OmiFilterOptions,SubnetFilterOptions,NetFilterOptions,BlockDevice"; DO NOT EDIT.
package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatBlockDevice is an auto-generated flat version of BlockDevice.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatBlockDevice struct {
	DeleteOnVmDeletion bool   `mapstructure:"delete_on_vm_deletion" cty:"delete_on_vm_deletion" hcl:"delete_on_vm_deletion,optional"`
	DeviceName         string `mapstructure:"device_name" cty:"device_name" hcl:"device_name,optional"`
	IOPS               int64  `mapstructure:"iops" cty:"iops" hcl:"iops,optional"`
	NoDevice           bool   `mapstructure:"no_device" cty:"no_device" hcl:"no_device,optional"`
	SnapshotId         string `mapstructure:"snapshot_id" cty:"snapshot_id" hcl:"snapshot_id,optional"`
	VirtualName        string `mapstructure:"virtual_name" cty:"virtual_name" hcl:"virtual_name,optional"`
	VolumeType         string `mapstructure:"volume_type" cty:"volume_type" hcl:"volume_type,optional"`
	VolumeSize         int64  `mapstructure:"volume_size" cty:"volume_size" hcl:"volume_size,optional"`
}

// FlatMapstructure returns a new FlatBlockDevice.
// FlatBlockDevice is an auto-generated flat version of BlockDevice.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*BlockDevice) FlatMapstructure() interface{} { return new(FlatBlockDevice) }

// HCL2Spec returns the hcldec.Spec of a BlockDevice.
// This spec is used by HCL to read the fields of BlockDevice.
func (*BlockDevice) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"DeleteOnVmDeletion": &hcldec.AttrSpec{Name: "delete_on_vm_deletion", Type: cty.Bool, Required: false},
		"DeviceName":         &hcldec.AttrSpec{Name: "device_name", Type: cty.String, Required: false},
		"IOPS":               &hcldec.AttrSpec{Name: "iops", Type: cty.Number, Required: false},
		"NoDevice":           &hcldec.AttrSpec{Name: "no_device", Type: cty.Bool, Required: false},
		"SnapshotId":         &hcldec.AttrSpec{Name: "snapshot_id", Type: cty.String, Required: false},
		"VirtualName":        &hcldec.AttrSpec{Name: "virtual_name", Type: cty.String, Required: false},
		"VolumeType":         &hcldec.AttrSpec{Name: "volume_type", Type: cty.String, Required: false},
		"VolumeSize":         &hcldec.AttrSpec{Name: "volume_size", Type: cty.Number, Required: false},
	}
	return s
}

// FlatNetFilterOptions is an auto-generated flat version of NetFilterOptions.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNetFilterOptions struct {
	Filters map[string]string `cty:"filters" hcl:"filters,optional"`
}

// FlatMapstructure returns a new FlatNetFilterOptions.
// FlatNetFilterOptions is an auto-generated flat version of NetFilterOptions.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NetFilterOptions) FlatMapstructure() interface{} { return new(FlatNetFilterOptions) }

// HCL2Spec returns the hcldec.Spec of a NetFilterOptions.
// This spec is used by HCL to read the fields of NetFilterOptions.
func (*NetFilterOptions) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Filters": &hcldec.BlockAttrsSpec{TypeName: "filters", ElementType: cty.String, Required: false},
	}
	return s
}

// FlatOmiFilterOptions is an auto-generated flat version of OmiFilterOptions.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatOmiFilterOptions struct {
	Filters    map[string]string `cty:"filters" hcl:"filters,optional"`
	Owners     []string          `cty:"owners" hcl:"owners,optional"`
	MostRecent bool              `mapstructure:"most_recent" cty:"most_recent" hcl:"most_recent,optional"`
}

// FlatMapstructure returns a new FlatOmiFilterOptions.
// FlatOmiFilterOptions is an auto-generated flat version of OmiFilterOptions.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*OmiFilterOptions) FlatMapstructure() interface{} { return new(FlatOmiFilterOptions) }

// HCL2Spec returns the hcldec.Spec of a OmiFilterOptions.
// This spec is used by HCL to read the fields of OmiFilterOptions.
func (*OmiFilterOptions) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Filters":    &hcldec.BlockAttrsSpec{TypeName: "filters", ElementType: cty.String, Required: false},
		"Owners":     &hcldec.AttrSpec{Name: "owners", Type: cty.List(cty.String), Required: false},
		"MostRecent": &hcldec.AttrSpec{Name: "most_recent", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatSecurityGroupFilterOptions is an auto-generated flat version of SecurityGroupFilterOptions.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatSecurityGroupFilterOptions struct {
	Filters map[string]string `cty:"filters" hcl:"filters,optional"`
}

// FlatMapstructure returns a new FlatSecurityGroupFilterOptions.
// FlatSecurityGroupFilterOptions is an auto-generated flat version of SecurityGroupFilterOptions.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*SecurityGroupFilterOptions) FlatMapstructure() interface{} {
	return new(FlatSecurityGroupFilterOptions)
}

// HCL2Spec returns the hcldec.Spec of a SecurityGroupFilterOptions.
// This spec is used by HCL to read the fields of SecurityGroupFilterOptions.
func (*SecurityGroupFilterOptions) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Filters": &hcldec.BlockAttrsSpec{TypeName: "filters", ElementType: cty.String, Required: false},
	}
	return s
}

// FlatSubnetFilterOptions is an auto-generated flat version of SubnetFilterOptions.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatSubnetFilterOptions struct {
	Filters  map[string]string `cty:"filters" hcl:"filters,optional"`
	MostFree bool              `mapstructure:"most_free" cty:"most_free" hcl:"most_free,optional"`
	Random   bool              `mapstructure:"random" cty:"random" hcl:"random,optional"`
}

// FlatMapstructure returns a new FlatSubnetFilterOptions.
// FlatSubnetFilterOptions is an auto-generated flat version of SubnetFilterOptions.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*SubnetFilterOptions) FlatMapstructure() interface{} { return new(FlatSubnetFilterOptions) }

// HCL2Spec returns the hcldec.Spec of a SubnetFilterOptions.
// This spec is used by HCL to read the fields of SubnetFilterOptions.
func (*SubnetFilterOptions) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Filters":  &hcldec.BlockAttrsSpec{TypeName: "filters", ElementType: cty.String, Required: false},
		"MostFree": &hcldec.AttrSpec{Name: "most_free", Type: cty.Bool, Required: false},
		"Random":   &hcldec.AttrSpec{Name: "random", Type: cty.Bool, Required: false},
	}
	return s
}
