// Code generated by "mapstructure-to-hcl2 -type Config"; DO NOT EDIT.
package bsu

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/hashicorp/packer/builder/osc/common"
	"github.com/zclconf/go-cty/cty"
	"time"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName             string                            `mapstructure:"packer_build_name" cty:"packer_build_name"`
	PackerBuilderType           string                            `mapstructure:"packer_builder_type" cty:"packer_builder_type"`
	PackerDebug                 bool                              `mapstructure:"packer_debug" cty:"packer_debug"`
	PackerForce                 bool                              `mapstructure:"packer_force" cty:"packer_force"`
	PackerOnError               string                            `mapstructure:"packer_on_error" cty:"packer_on_error"`
	PackerUserVars              map[string]string                 `mapstructure:"packer_user_variables" cty:"packer_user_variables"`
	PackerSensitiveVars         []string                          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables"`
	AccessKey                   string                            `mapstructure:"access_key" cty:"access_key"`
	CustomEndpointOAPI          string                            `mapstructure:"custom_endpoint_oapi" cty:"custom_endpoint_oapi"`
	InsecureSkipTLSVerify       bool                              `mapstructure:"insecure_skip_tls_verify" cty:"insecure_skip_tls_verify"`
	MFACode                     string                            `mapstructure:"mfa_code" cty:"mfa_code"`
	ProfileName                 string                            `mapstructure:"profile" cty:"profile"`
	RawRegion                   string                            `mapstructure:"region" cty:"region"`
	SecretKey                   string                            `mapstructure:"secret_key" cty:"secret_key"`
	SkipValidation              bool                              `mapstructure:"skip_region_validation" cty:"skip_region_validation"`
	SkipMetadataApiCheck        bool                              `mapstructure:"skip_metadata_api_check" cty:"skip_metadata_api_check"`
	Token                       string                            `mapstructure:"token" cty:"token"`
	OMIName                     string                            `mapstructure:"omi_name" cty:"omi_name"`
	OMIDescription              string                            `mapstructure:"omi_description" cty:"omi_description"`
	OMIVirtType                 string                            `mapstructure:"omi_virtualization_type" cty:"omi_virtualization_type"`
	OMIAccountIDs               []string                          `mapstructure:"omi_account_ids" cty:"omi_account_ids"`
	OMIGroups                   []string                          `mapstructure:"omi_groups" cty:"omi_groups"`
	OMIProductCodes             []string                          `mapstructure:"omi_product_codes" cty:"omi_product_codes"`
	OMIRegions                  []string                          `mapstructure:"omi_regions" cty:"omi_regions"`
	OMISkipRegionValidation     bool                              `mapstructure:"skip_region_validation" cty:"skip_region_validation"`
	OMITags                     common.TagMap                     `mapstructure:"tags" cty:"tags"`
	OMIForceDeregister          bool                              `mapstructure:"force_deregister" cty:"force_deregister"`
	OMIForceDeleteSnapshot      bool                              `mapstructure:"force_delete_snapshot" cty:"force_delete_snapshot"`
	SnapshotTags                common.TagMap                     `mapstructure:"snapshot_tags" cty:"snapshot_tags"`
	SnapshotAccountIDs          []string                          `mapstructure:"snapshot_account_ids" cty:"snapshot_account_ids"`
	SnapshotGroups              []string                          `mapstructure:"snapshot_groups" cty:"snapshot_groups"`
	OMIMappings                 []common.BlockDevice              `mapstructure:"omi_block_device_mappings" cty:"omi_block_device_mappings"`
	LaunchMappings              []common.BlockDevice              `mapstructure:"launch_block_device_mappings" cty:"launch_block_device_mappings"`
	AssociatePublicIpAddress    bool                              `mapstructure:"associate_public_ip_address" cty:"associate_public_ip_address"`
	Subregion                   string                            `mapstructure:"subregion_name" cty:"subregion_name"`
	BlockDurationMinutes        int64                             `mapstructure:"block_duration_minutes" cty:"block_duration_minutes"`
	DisableStopVm               bool                              `mapstructure:"disable_stop_vm" cty:"disable_stop_vm"`
	BsuOptimized                bool                              `mapstructure:"bsu_optimized" cty:"bsu_optimized"`
	EnableT2Unlimited           bool                              `mapstructure:"enable_t2_unlimited" cty:"enable_t2_unlimited"`
	IamVmProfile                string                            `mapstructure:"iam_vm_profile" cty:"iam_vm_profile"`
	VmInitiatedShutdownBehavior string                            `mapstructure:"shutdown_behavior" cty:"shutdown_behavior"`
	VmType                      string                            `mapstructure:"vm_type" cty:"vm_type"`
	SecurityGroupFilter         common.SecurityGroupFilterOptions `mapstructure:"security_group_filter" cty:"security_group_filter"`
	RunTags                     map[string]string                 `mapstructure:"run_tags" cty:"run_tags"`
	SecurityGroupId             string                            `mapstructure:"security_group_id" cty:"security_group_id"`
	SecurityGroupIds            []string                          `mapstructure:"security_group_ids" cty:"security_group_ids"`
	SourceOmi                   string                            `mapstructure:"source_omi" cty:"source_omi"`
	SourceOmiFilter             common.OmiFilterOptions           `mapstructure:"source_omi_filter" cty:"source_omi_filter"`
	SpotPrice                   string                            `mapstructure:"spot_price" cty:"spot_price"`
	SpotPriceAutoProduct        string                            `mapstructure:"spot_price_auto_product" cty:"spot_price_auto_product"`
	SpotTags                    map[string]string                 `mapstructure:"spot_tags" cty:"spot_tags"`
	SubnetFilter                common.SubnetFilterOptions        `mapstructure:"subnet_filter" cty:"subnet_filter"`
	SubnetId                    string                            `mapstructure:"subnet_id" cty:"subnet_id"`
	TemporaryKeyPairName        string                            `mapstructure:"temporary_key_pair_name" cty:"temporary_key_pair_name"`
	TemporarySGSourceCidr       string                            `mapstructure:"temporary_security_group_source_cidr" cty:"temporary_security_group_source_cidr"`
	UserData                    string                            `mapstructure:"user_data" cty:"user_data"`
	UserDataFile                string                            `mapstructure:"user_data_file" cty:"user_data_file"`
	NetFilter                   common.NetFilterOptions           `mapstructure:"net_filter" cty:"net_filter"`
	NetId                       string                            `mapstructure:"net_id" cty:"net_id"`
	WindowsPasswordTimeout      time.Duration                     `mapstructure:"windows_password_timeout" cty:"windows_password_timeout"`
	Type                        string                            `mapstructure:"communicator" cty:"communicator"`
	PauseBeforeConnect          time.Duration                     `mapstructure:"pause_before_connecting" cty:"pause_before_connecting"`
	SSHHost                     string                            `mapstructure:"ssh_host" cty:"ssh_host"`
	SSHPort                     int                               `mapstructure:"ssh_port" cty:"ssh_port"`
	SSHUsername                 string                            `mapstructure:"ssh_username" cty:"ssh_username"`
	SSHPassword                 string                            `mapstructure:"ssh_password" cty:"ssh_password"`
	SSHKeyPairName              string                            `mapstructure:"ssh_keypair_name" cty:"ssh_keypair_name"`
	SSHTemporaryKeyPairName     string                            `mapstructure:"temporary_key_pair_name" cty:"temporary_key_pair_name"`
	SSHClearAuthorizedKeys      bool                              `mapstructure:"ssh_clear_authorized_keys" cty:"ssh_clear_authorized_keys"`
	SSHPrivateKeyFile           string                            `mapstructure:"ssh_private_key_file" cty:"ssh_private_key_file"`
	SSHPty                      bool                              `mapstructure:"ssh_pty" cty:"ssh_pty"`
	SSHTimeout                  time.Duration                     `mapstructure:"ssh_timeout" cty:"ssh_timeout"`
	SSHAgentAuth                bool                              `mapstructure:"ssh_agent_auth" cty:"ssh_agent_auth"`
	SSHDisableAgentForwarding   bool                              `mapstructure:"ssh_disable_agent_forwarding" cty:"ssh_disable_agent_forwarding"`
	SSHHandshakeAttempts        int                               `mapstructure:"ssh_handshake_attempts" cty:"ssh_handshake_attempts"`
	SSHBastionHost              string                            `mapstructure:"ssh_bastion_host" cty:"ssh_bastion_host"`
	SSHBastionPort              int                               `mapstructure:"ssh_bastion_port" cty:"ssh_bastion_port"`
	SSHBastionAgentAuth         bool                              `mapstructure:"ssh_bastion_agent_auth" cty:"ssh_bastion_agent_auth"`
	SSHBastionUsername          string                            `mapstructure:"ssh_bastion_username" cty:"ssh_bastion_username"`
	SSHBastionPassword          string                            `mapstructure:"ssh_bastion_password" cty:"ssh_bastion_password"`
	SSHBastionPrivateKeyFile    string                            `mapstructure:"ssh_bastion_private_key_file" cty:"ssh_bastion_private_key_file"`
	SSHFileTransferMethod       string                            `mapstructure:"ssh_file_transfer_method" cty:"ssh_file_transfer_method"`
	SSHProxyHost                string                            `mapstructure:"ssh_proxy_host" cty:"ssh_proxy_host"`
	SSHProxyPort                int                               `mapstructure:"ssh_proxy_port" cty:"ssh_proxy_port"`
	SSHProxyUsername            string                            `mapstructure:"ssh_proxy_username" cty:"ssh_proxy_username"`
	SSHProxyPassword            string                            `mapstructure:"ssh_proxy_password" cty:"ssh_proxy_password"`
	SSHKeepAliveInterval        time.Duration                     `mapstructure:"ssh_keep_alive_interval" cty:"ssh_keep_alive_interval"`
	SSHReadWriteTimeout         time.Duration                     `mapstructure:"ssh_read_write_timeout" cty:"ssh_read_write_timeout"`
	SSHRemoteTunnels            []string                          `mapstructure:"ssh_remote_tunnels" cty:"ssh_remote_tunnels"`
	SSHLocalTunnels             []string                          `mapstructure:"ssh_local_tunnels" cty:"ssh_local_tunnels"`
	SSHPublicKey                []byte                            `cty:"ssh_public_key"`
	SSHPrivateKey               []byte                            `cty:"ssh_private_key"`
	WinRMUser                   string                            `mapstructure:"winrm_username" cty:"winrm_username"`
	WinRMPassword               string                            `mapstructure:"winrm_password" cty:"winrm_password"`
	WinRMHost                   string                            `mapstructure:"winrm_host" cty:"winrm_host"`
	WinRMPort                   int                               `mapstructure:"winrm_port" cty:"winrm_port"`
	WinRMTimeout                time.Duration                     `mapstructure:"winrm_timeout" cty:"winrm_timeout"`
	WinRMUseSSL                 bool                              `mapstructure:"winrm_use_ssl" cty:"winrm_use_ssl"`
	WinRMInsecure               bool                              `mapstructure:"winrm_insecure" cty:"winrm_insecure"`
	WinRMUseNTLM                bool                              `mapstructure:"winrm_use_ntlm" cty:"winrm_use_ntlm"`
	SSHInterface                string                            `mapstructure:"ssh_interface" cty:"ssh_interface"`
	VolumeRunTags               common.TagMap                     `mapstructure:"run_volume_tags" cty:"run_volume_tags"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{} { return new(FlatConfig) }

// HCL2Spec returns the hcldec.Spec of a Config.
// This spec is used by HCL to read the fields of Config.
func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PackerBuildName":             &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"PackerBuilderType":           &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"PackerDebug":                 &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"PackerForce":                 &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"PackerOnError":               &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"PackerUserVars":              &hcldec.BlockAttrsSpec{TypeName: "packer_user_variables", ElementType: cty.String, Required: false},
		"PackerSensitiveVars":         &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"AccessKey":                   &hcldec.AttrSpec{Name: "access_key", Type: cty.String, Required: false},
		"CustomEndpointOAPI":          &hcldec.AttrSpec{Name: "custom_endpoint_oapi", Type: cty.String, Required: false},
		"InsecureSkipTLSVerify":       &hcldec.AttrSpec{Name: "insecure_skip_tls_verify", Type: cty.Bool, Required: false},
		"MFACode":                     &hcldec.AttrSpec{Name: "mfa_code", Type: cty.String, Required: false},
		"ProfileName":                 &hcldec.AttrSpec{Name: "profile", Type: cty.String, Required: false},
		"RawRegion":                   &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"SecretKey":                   &hcldec.AttrSpec{Name: "secret_key", Type: cty.String, Required: false},
		"SkipValidation":              &hcldec.AttrSpec{Name: "skip_region_validation", Type: cty.Bool, Required: false},
		"SkipMetadataApiCheck":        &hcldec.AttrSpec{Name: "skip_metadata_api_check", Type: cty.Bool, Required: false},
		"Token":                       &hcldec.AttrSpec{Name: "token", Type: cty.String, Required: false},
		"OMIName":                     &hcldec.AttrSpec{Name: "omi_name", Type: cty.String, Required: false},
		"OMIDescription":              &hcldec.AttrSpec{Name: "omi_description", Type: cty.String, Required: false},
		"OMIVirtType":                 &hcldec.AttrSpec{Name: "omi_virtualization_type", Type: cty.String, Required: false},
		"OMIAccountIDs":               &hcldec.AttrSpec{Name: "omi_account_ids", Type: cty.List(cty.String), Required: false},
		"OMIGroups":                   &hcldec.AttrSpec{Name: "omi_groups", Type: cty.List(cty.String), Required: false},
		"OMIProductCodes":             &hcldec.AttrSpec{Name: "omi_product_codes", Type: cty.List(cty.String), Required: false},
		"OMIRegions":                  &hcldec.AttrSpec{Name: "omi_regions", Type: cty.List(cty.String), Required: false},
		"OMISkipRegionValidation":     &hcldec.AttrSpec{Name: "skip_region_validation", Type: cty.Bool, Required: false},
		"OMITags":                     &hcldec.BlockAttrsSpec{TypeName: "common.TagMap", ElementType: cty.String, Required: false},
		"OMIForceDeregister":          &hcldec.AttrSpec{Name: "force_deregister", Type: cty.Bool, Required: false},
		"OMIForceDeleteSnapshot":      &hcldec.AttrSpec{Name: "force_delete_snapshot", Type: cty.Bool, Required: false},
		"SnapshotTags":                &hcldec.BlockAttrsSpec{TypeName: "common.TagMap", ElementType: cty.String, Required: false},
		"SnapshotAccountIDs":          &hcldec.AttrSpec{Name: "snapshot_account_ids", Type: cty.List(cty.String), Required: false},
		"SnapshotGroups":              &hcldec.AttrSpec{Name: "snapshot_groups", Type: cty.List(cty.String), Required: false},
		"OMIMappings":                 &hcldec.BlockListSpec{TypeName: "[]common.BlockDevice", Nested: &hcldec.BlockObjectSpec{TypeName: "common.BlockDevice", Nested: hcldec.ObjectSpec((*common.BlockDevice)(nil).HCL2Spec())}},
		"LaunchMappings":              &hcldec.BlockListSpec{TypeName: "[]common.BlockDevice", Nested: &hcldec.BlockObjectSpec{TypeName: "common.BlockDevice", Nested: hcldec.ObjectSpec((*common.BlockDevice)(nil).HCL2Spec())}},
		"AssociatePublicIpAddress":    &hcldec.AttrSpec{Name: "associate_public_ip_address", Type: cty.Bool, Required: false},
		"Subregion":                   &hcldec.AttrSpec{Name: "subregion_name", Type: cty.String, Required: false},
		"BlockDurationMinutes":        &hcldec.AttrSpec{Name: "block_duration_minutes", Type: cty.Number, Required: false},
		"DisableStopVm":               &hcldec.AttrSpec{Name: "disable_stop_vm", Type: cty.Bool, Required: false},
		"BsuOptimized":                &hcldec.AttrSpec{Name: "bsu_optimized", Type: cty.Bool, Required: false},
		"EnableT2Unlimited":           &hcldec.AttrSpec{Name: "enable_t2_unlimited", Type: cty.Bool, Required: false},
		"IamVmProfile":                &hcldec.AttrSpec{Name: "iam_vm_profile", Type: cty.String, Required: false},
		"VmInitiatedShutdownBehavior": &hcldec.AttrSpec{Name: "shutdown_behavior", Type: cty.String, Required: false},
		"VmType":                      &hcldec.AttrSpec{Name: "vm_type", Type: cty.String, Required: false},
		"SecurityGroupFilter":         &hcldec.BlockObjectSpec{TypeName: "common.SecurityGroupFilterOptions", Nested: hcldec.ObjectSpec((*common.SecurityGroupFilterOptions)(nil).HCL2Spec())},
		"RunTags":                     &hcldec.BlockAttrsSpec{TypeName: "run_tags", ElementType: cty.String, Required: false},
		"SecurityGroupId":             &hcldec.AttrSpec{Name: "security_group_id", Type: cty.String, Required: false},
		"SecurityGroupIds":            &hcldec.AttrSpec{Name: "security_group_ids", Type: cty.List(cty.String), Required: false},
		"SourceOmi":                   &hcldec.AttrSpec{Name: "source_omi", Type: cty.String, Required: false},
		"SourceOmiFilter":             &hcldec.BlockObjectSpec{TypeName: "common.OmiFilterOptions", Nested: hcldec.ObjectSpec((*common.OmiFilterOptions)(nil).HCL2Spec())},
		"SpotPrice":                   &hcldec.AttrSpec{Name: "spot_price", Type: cty.String, Required: false},
		"SpotPriceAutoProduct":        &hcldec.AttrSpec{Name: "spot_price_auto_product", Type: cty.String, Required: false},
		"SpotTags":                    &hcldec.BlockAttrsSpec{TypeName: "spot_tags", ElementType: cty.String, Required: false},
		"SubnetFilter":                &hcldec.BlockObjectSpec{TypeName: "common.SubnetFilterOptions", Nested: hcldec.ObjectSpec((*common.SubnetFilterOptions)(nil).HCL2Spec())},
		"SubnetId":                    &hcldec.AttrSpec{Name: "subnet_id", Type: cty.String, Required: false},
		"TemporaryKeyPairName":        &hcldec.AttrSpec{Name: "temporary_key_pair_name", Type: cty.String, Required: false},
		"TemporarySGSourceCidr":       &hcldec.AttrSpec{Name: "temporary_security_group_source_cidr", Type: cty.String, Required: false},
		"UserData":                    &hcldec.AttrSpec{Name: "user_data", Type: cty.String, Required: false},
		"UserDataFile":                &hcldec.AttrSpec{Name: "user_data_file", Type: cty.String, Required: false},
		"NetFilter":                   &hcldec.BlockObjectSpec{TypeName: "common.NetFilterOptions", Nested: hcldec.ObjectSpec((*common.NetFilterOptions)(nil).HCL2Spec())},
		"NetId":                       &hcldec.AttrSpec{Name: "net_id", Type: cty.String, Required: false},
		"WindowsPasswordTimeout":      &hcldec.AttrSpec{Name: "windows_password_timeout", Type: cty.String, Required: false},
		"Type":                        &hcldec.AttrSpec{Name: "communicator", Type: cty.String, Required: false},
		"PauseBeforeConnect":          &hcldec.AttrSpec{Name: "pause_before_connecting", Type: cty.String, Required: false},
		"SSHHost":                     &hcldec.AttrSpec{Name: "ssh_host", Type: cty.String, Required: false},
		"SSHPort":                     &hcldec.AttrSpec{Name: "ssh_port", Type: cty.Number, Required: false},
		"SSHUsername":                 &hcldec.AttrSpec{Name: "ssh_username", Type: cty.String, Required: false},
		"SSHPassword":                 &hcldec.AttrSpec{Name: "ssh_password", Type: cty.String, Required: false},
		"SSHKeyPairName":              &hcldec.AttrSpec{Name: "ssh_keypair_name", Type: cty.String, Required: false},
		"SSHTemporaryKeyPairName":     &hcldec.AttrSpec{Name: "temporary_key_pair_name", Type: cty.String, Required: false},
		"SSHClearAuthorizedKeys":      &hcldec.AttrSpec{Name: "ssh_clear_authorized_keys", Type: cty.Bool, Required: false},
		"SSHPrivateKeyFile":           &hcldec.AttrSpec{Name: "ssh_private_key_file", Type: cty.String, Required: false},
		"SSHPty":                      &hcldec.AttrSpec{Name: "ssh_pty", Type: cty.Bool, Required: false},
		"SSHTimeout":                  &hcldec.AttrSpec{Name: "ssh_timeout", Type: cty.String, Required: false},
		"SSHAgentAuth":                &hcldec.AttrSpec{Name: "ssh_agent_auth", Type: cty.Bool, Required: false},
		"SSHDisableAgentForwarding":   &hcldec.AttrSpec{Name: "ssh_disable_agent_forwarding", Type: cty.Bool, Required: false},
		"SSHHandshakeAttempts":        &hcldec.AttrSpec{Name: "ssh_handshake_attempts", Type: cty.Number, Required: false},
		"SSHBastionHost":              &hcldec.AttrSpec{Name: "ssh_bastion_host", Type: cty.String, Required: false},
		"SSHBastionPort":              &hcldec.AttrSpec{Name: "ssh_bastion_port", Type: cty.Number, Required: false},
		"SSHBastionAgentAuth":         &hcldec.AttrSpec{Name: "ssh_bastion_agent_auth", Type: cty.Bool, Required: false},
		"SSHBastionUsername":          &hcldec.AttrSpec{Name: "ssh_bastion_username", Type: cty.String, Required: false},
		"SSHBastionPassword":          &hcldec.AttrSpec{Name: "ssh_bastion_password", Type: cty.String, Required: false},
		"SSHBastionPrivateKeyFile":    &hcldec.AttrSpec{Name: "ssh_bastion_private_key_file", Type: cty.String, Required: false},
		"SSHFileTransferMethod":       &hcldec.AttrSpec{Name: "ssh_file_transfer_method", Type: cty.String, Required: false},
		"SSHProxyHost":                &hcldec.AttrSpec{Name: "ssh_proxy_host", Type: cty.String, Required: false},
		"SSHProxyPort":                &hcldec.AttrSpec{Name: "ssh_proxy_port", Type: cty.Number, Required: false},
		"SSHProxyUsername":            &hcldec.AttrSpec{Name: "ssh_proxy_username", Type: cty.String, Required: false},
		"SSHProxyPassword":            &hcldec.AttrSpec{Name: "ssh_proxy_password", Type: cty.String, Required: false},
		"SSHKeepAliveInterval":        &hcldec.AttrSpec{Name: "ssh_keep_alive_interval", Type: cty.String, Required: false},
		"SSHReadWriteTimeout":         &hcldec.AttrSpec{Name: "ssh_read_write_timeout", Type: cty.String, Required: false},
		"SSHRemoteTunnels":            &hcldec.AttrSpec{Name: "ssh_remote_tunnels", Type: cty.List(cty.String), Required: false},
		"SSHLocalTunnels":             &hcldec.AttrSpec{Name: "ssh_local_tunnels", Type: cty.List(cty.String), Required: false},
		"SSHPublicKey":                &hcldec.AttrSpec{Name: "ssh_public_key", Type: cty.List(cty.Number), Required: false},
		"SSHPrivateKey":               &hcldec.AttrSpec{Name: "ssh_private_key", Type: cty.List(cty.Number), Required: false},
		"WinRMUser":                   &hcldec.AttrSpec{Name: "winrm_username", Type: cty.String, Required: false},
		"WinRMPassword":               &hcldec.AttrSpec{Name: "winrm_password", Type: cty.String, Required: false},
		"WinRMHost":                   &hcldec.AttrSpec{Name: "winrm_host", Type: cty.String, Required: false},
		"WinRMPort":                   &hcldec.AttrSpec{Name: "winrm_port", Type: cty.Number, Required: false},
		"WinRMTimeout":                &hcldec.AttrSpec{Name: "winrm_timeout", Type: cty.String, Required: false},
		"WinRMUseSSL":                 &hcldec.AttrSpec{Name: "winrm_use_ssl", Type: cty.Bool, Required: false},
		"WinRMInsecure":               &hcldec.AttrSpec{Name: "winrm_insecure", Type: cty.Bool, Required: false},
		"WinRMUseNTLM":                &hcldec.AttrSpec{Name: "winrm_use_ntlm", Type: cty.Bool, Required: false},
		"SSHInterface":                &hcldec.AttrSpec{Name: "ssh_interface", Type: cty.String, Required: false},
		"VolumeRunTags":               &hcldec.BlockAttrsSpec{TypeName: "common.TagMap", ElementType: cty.String, Required: false},
	}
	return s
}
