// Code generated by "mapstructure-to-hcl2 -type tencentCloudDataDisk"; DO NOT EDIT.
package cvm

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

type FlattencentCloudDataDisk struct {
	DiskType   string `mapstructure:"disk_type" cty:"disk_type"`
	DiskSize   int64  `mapstructure:"disk_size" cty:"disk_size"`
	SnapshotId string `mapstructure:"disk_snapshot_id" cty:"disk_snapshot_id"`
}

func (*tencentCloudDataDisk) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"DiskType":   &hcldec.AttrSpec{Name: "disk_type", Type: cty.String, Required: false},
		"DiskSize":   &hcldec.AttrSpec{Name: "disk_size", Type: cty.Number, Required: false},
		"SnapshotId": &hcldec.AttrSpec{Name: "disk_snapshot_id", Type: cty.String, Required: false},
	}
	return s
}
