// Code generated by "mapstructure-to-hcl2 -type PVConfig"; DO NOT EDIT.
package classic

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/hashicorp/packer/helper/communicator"
	"github.com/zclconf/go-cty/cty"
)

type FlatPVConfig struct {
	PersistentVolumeSize      int                 `mapstructure:"persistent_volume_size" cty:"persistent_volume_size"`
	BuilderUploadImageCommand string              `mapstructure:"builder_upload_image_command" cty:"builder_upload_image_command"`
	BuilderShape              string              `mapstructure:"builder_shape" cty:"builder_shape"`
	BuilderImageList          string              `mapstructure:"builder_image_list" cty:"builder_image_list"`
	BuilderImageListEntry     *int                `mapstructure:"builder_image_list_entry" cty:"builder_image_list_entry"`
	BuilderComm               communicator.Config `mapstructure:"builder_communicator" cty:"builder_communicator"`
}

func (*PVConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PersistentVolumeSize":      &hcldec.AttrSpec{Name: "persistent_volume_size", Type: cty.Number, Required: false},
		"BuilderUploadImageCommand": &hcldec.AttrSpec{Name: "builder_upload_image_command", Type: cty.String, Required: false},
		"BuilderShape":              &hcldec.AttrSpec{Name: "builder_shape", Type: cty.String, Required: false},
		"BuilderImageList":          &hcldec.AttrSpec{Name: "builder_image_list", Type: cty.String, Required: false},
		"BuilderImageListEntry":     nil, /* not basic */
		"BuilderComm":               &hcldec.BlockObjectSpec{TypeName: "communicator.Config", Nested: hcldec.ObjectSpec((*communicator.Config)(nil).HCL2Spec())},
	}
	return s
}

type FlatPVConfig struct {
	PersistentVolumeSize      int                 `mapstructure:"persistent_volume_size" cty:"persistent_volume_size"`
	BuilderUploadImageCommand string              `mapstructure:"builder_upload_image_command" cty:"builder_upload_image_command"`
	BuilderShape              string              `mapstructure:"builder_shape" cty:"builder_shape"`
	BuilderImageList          string              `mapstructure:"builder_image_list" cty:"builder_image_list"`
	BuilderImageListEntry     *int                `mapstructure:"builder_image_list_entry" cty:"builder_image_list_entry"`
	BuilderComm               communicator.Config `mapstructure:"builder_communicator" cty:"builder_communicator"`
}

func (*PVConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PersistentVolumeSize":      &hcldec.AttrSpec{Name: "persistent_volume_size", Type: cty.Number, Required: false},
		"BuilderUploadImageCommand": &hcldec.AttrSpec{Name: "builder_upload_image_command", Type: cty.String, Required: false},
		"BuilderShape":              &hcldec.AttrSpec{Name: "builder_shape", Type: cty.String, Required: false},
		"BuilderImageList":          &hcldec.AttrSpec{Name: "builder_image_list", Type: cty.String, Required: false},
		"BuilderImageListEntry":     nil, /* not basic */
		"BuilderComm":               &hcldec.BlockObjectSpec{TypeName: "communicator.Config", Nested: hcldec.ObjectSpec((*communicator.Config)(nil).HCL2Spec())},
	}
	return s
}
