// Code generated by "mapstructure-to-hcl2 -type Config"; DO NOT EDIT.
package googlecomputeimport

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

type FlatConfig struct {
	PackerBuildName      string            `mapstructure:"packer_build_name" cty:"packer_build_name"`
	PackerBuilderType    string            `mapstructure:"packer_builder_type" cty:"packer_builder_type"`
	PackerDebug          bool              `mapstructure:"packer_debug" cty:"packer_debug"`
	PackerForce          bool              `mapstructure:"packer_force" cty:"packer_force"`
	PackerOnError        string            `mapstructure:"packer_on_error" cty:"packer_on_error"`
	PackerUserVars       map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables"`
	PackerSensitiveVars  []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables"`
	AccountFile          string            `mapstructure:"account_file" cty:"account_file"`
	ProjectId            string            `mapstructure:"project_id" cty:"project_id"`
	Bucket               string            `mapstructure:"bucket" cty:"bucket"`
	GCSObjectName        string            `mapstructure:"gcs_object_name" cty:"gcs_object_name"`
	ImageDescription     string            `mapstructure:"image_description" cty:"image_description"`
	ImageFamily          string            `mapstructure:"image_family" cty:"image_family"`
	ImageGuestOsFeatures []string          `mapstructure:"image_guest_os_features" cty:"image_guest_os_features"`
	ImageLabels          map[string]string `mapstructure:"image_labels" cty:"image_labels"`
	ImageName            string            `mapstructure:"image_name" cty:"image_name"`
	SkipClean            bool              `mapstructure:"skip_clean" cty:"skip_clean"`
	VaultGCPOauthEngine  string            `mapstructure:"vault_gcp_oauth_engine" cty:"vault_gcp_oauth_engine"`
}

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PackerBuildName":      &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"PackerBuilderType":    &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"PackerDebug":          &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"PackerForce":          &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"PackerOnError":        &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"PackerUserVars":       &hcldec.BlockAttrsSpec{TypeName: "packer_user_variables", ElementType: cty.String, Required: false},
		"PackerSensitiveVars":  &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"AccountFile":          &hcldec.AttrSpec{Name: "account_file", Type: cty.String, Required: false},
		"ProjectId":            &hcldec.AttrSpec{Name: "project_id", Type: cty.String, Required: false},
		"Bucket":               &hcldec.AttrSpec{Name: "bucket", Type: cty.String, Required: false},
		"GCSObjectName":        &hcldec.AttrSpec{Name: "gcs_object_name", Type: cty.String, Required: false},
		"ImageDescription":     &hcldec.AttrSpec{Name: "image_description", Type: cty.String, Required: false},
		"ImageFamily":          &hcldec.AttrSpec{Name: "image_family", Type: cty.String, Required: false},
		"ImageGuestOsFeatures": &hcldec.AttrSpec{Name: "image_guest_os_features", Type: cty.List(cty.String), Required: false},
		"ImageLabels":          &hcldec.BlockAttrsSpec{TypeName: "image_labels", ElementType: cty.String, Required: false},
		"ImageName":            &hcldec.AttrSpec{Name: "image_name", Type: cty.String, Required: false},
		"SkipClean":            &hcldec.AttrSpec{Name: "skip_clean", Type: cty.Bool, Required: false},
		"VaultGCPOauthEngine":  &hcldec.AttrSpec{Name: "vault_gcp_oauth_engine", Type: cty.String, Required: false},
	}
	return s
}
