// Code generated by "mapstructure-to-hcl2 -type ExportConfig"; DO NOT EDIT.
package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

type FlatExportConfig struct {
	Format     string   `mapstructure:"format" required:"false" cty:"format"`
	ExportOpts []string `mapstructure:"export_opts" required:"false" cty:"export_opts"`
}

func (*ExportConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"Format":     &hcldec.AttrSpec{Name: "format", Type: cty.String, Required: false},
		"ExportOpts": &hcldec.AttrSpec{Name: "export_opts", Type: cty.List(cty.String), Required: false},
	}
	return s
}
