// Code generated by "mapstructure-to-hcl2 -type PrlctlVersionConfig"; DO NOT EDIT.
package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

type FlatPrlctlVersionConfig struct {
	PrlctlVersionFile string `mapstructure:"prlctl_version_file" required:"false" cty:"prlctl_version_file"`
}

func (*PrlctlVersionConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PrlctlVersionFile": &hcldec.AttrSpec{Name: "prlctl_version_file", Type: cty.String, Required: false},
	}
	return s
}
