// Code generated by "mapstructure-to-hcl2 -type Config"; DO NOT EDIT.
package exoscaleimport

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName         string            `mapstructure:"packer_build_name" cty:"packer_build_name"`
	PackerBuilderType       string            `mapstructure:"packer_builder_type" cty:"packer_builder_type"`
	PackerDebug             bool              `mapstructure:"packer_debug" cty:"packer_debug"`
	PackerForce             bool              `mapstructure:"packer_force" cty:"packer_force"`
	PackerOnError           string            `mapstructure:"packer_on_error" cty:"packer_on_error"`
	PackerUserVars          map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables"`
	PackerSensitiveVars     []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables"`
	SkipClean               bool              `mapstructure:"skip_clean" cty:"skip_clean"`
	SOSEndpoint             string            `mapstructure:"sos_endpoint" cty:"sos_endpoint"`
	APIEndpoint             string            `mapstructure:"api_endpoint" cty:"api_endpoint"`
	APIKey                  string            `mapstructure:"api_key" cty:"api_key"`
	APISecret               string            `mapstructure:"api_secret" cty:"api_secret"`
	ImageBucket             string            `mapstructure:"image_bucket" cty:"image_bucket"`
	TemplateZone            string            `mapstructure:"template_zone" cty:"template_zone"`
	TemplateName            string            `mapstructure:"template_name" cty:"template_name"`
	TemplateDescription     string            `mapstructure:"template_description" cty:"template_description"`
	TemplateUsername        string            `mapstructure:"template_username" cty:"template_username"`
	TemplateDisablePassword bool              `mapstructure:"template_disable_password" cty:"template_disable_password"`
	TemplateDisableSSHKey   bool              `mapstructure:"template_disable_sshkey" cty:"template_disable_sshkey"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{} { return new(FlatConfig) }

// HCL2Spec returns the hcldec.Spec of a Config.
// This spec is used by HCL to read the fields of Config.
func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PackerBuildName":         &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"PackerBuilderType":       &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"PackerDebug":             &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"PackerForce":             &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"PackerOnError":           &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"PackerUserVars":          &hcldec.BlockAttrsSpec{TypeName: "packer_user_variables", ElementType: cty.String, Required: false},
		"PackerSensitiveVars":     &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"SkipClean":               &hcldec.AttrSpec{Name: "skip_clean", Type: cty.Bool, Required: false},
		"SOSEndpoint":             &hcldec.AttrSpec{Name: "sos_endpoint", Type: cty.String, Required: false},
		"APIEndpoint":             &hcldec.AttrSpec{Name: "api_endpoint", Type: cty.String, Required: false},
		"APIKey":                  &hcldec.AttrSpec{Name: "api_key", Type: cty.String, Required: false},
		"APISecret":               &hcldec.AttrSpec{Name: "api_secret", Type: cty.String, Required: false},
		"ImageBucket":             &hcldec.AttrSpec{Name: "image_bucket", Type: cty.String, Required: false},
		"TemplateZone":            &hcldec.AttrSpec{Name: "template_zone", Type: cty.String, Required: false},
		"TemplateName":            &hcldec.AttrSpec{Name: "template_name", Type: cty.String, Required: false},
		"TemplateDescription":     &hcldec.AttrSpec{Name: "template_description", Type: cty.String, Required: false},
		"TemplateUsername":        &hcldec.AttrSpec{Name: "template_username", Type: cty.String, Required: false},
		"TemplateDisablePassword": &hcldec.AttrSpec{Name: "template_disable_password", Type: cty.Bool, Required: false},
		"TemplateDisableSSHKey":   &hcldec.AttrSpec{Name: "template_disable_sshkey", Type: cty.Bool, Required: false},
	}
	return s
}
