// Code generated by "mapstructure-to-hcl2 -type ShutdownConfig"; DO NOT EDIT.
package shutdowncommand

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
	"time"
)

type FlatShutdownConfig struct {
	ShutdownCommand    string        `mapstructure:"shutdown_command" required:"false" cty:"shutdown_command"`
	RawShutdownTimeout string        `mapstructure:"shutdown_timeout" required:"false" cty:"shutdown_timeout"`
	ShutdownTimeout    time.Duration `cty:"shutdown_timeout"`
}

func (*ShutdownConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"ShutdownCommand":    &hcldec.AttrSpec{Name: "shutdown_command", Type: cty.String, Required: false},
		"RawShutdownTimeout": &hcldec.AttrSpec{Name: "shutdown_timeout", Type: cty.String, Required: false},
		"ShutdownTimeout":    &hcldec.AttrSpec{Name: "shutdown_timeout", Type: cty.String, Required: false},
	}
	return s
}
