// Code generated by "mapstructure-to-hcl2 -type Config"; DO NOT EDIT.
package vmcx

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
	"time"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName                string            `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name,optional"`
	PackerBuilderType              string            `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type,optional"`
	PackerDebug                    bool              `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug,optional"`
	PackerForce                    bool              `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force,optional"`
	PackerOnError                  string            `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error,optional"`
	PackerUserVars                 map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables,optional"`
	PackerSensitiveVars            []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables,optional"`
	HTTPDir                        string            `mapstructure:"http_directory" cty:"http_directory" hcl:"http_directory,optional"`
	HTTPPortMin                    int               `mapstructure:"http_port_min" cty:"http_port_min" hcl:"http_port_min,optional"`
	HTTPPortMax                    int               `mapstructure:"http_port_max" cty:"http_port_max" hcl:"http_port_max,optional"`
	ISOChecksum                    string            `mapstructure:"iso_checksum" required:"true" cty:"iso_checksum" hcl:"iso_checksum,optional"`
	ISOChecksumURL                 string            `mapstructure:"iso_checksum_url" cty:"iso_checksum_url" hcl:"iso_checksum_url,optional"`
	ISOChecksumType                string            `mapstructure:"iso_checksum_type" cty:"iso_checksum_type" hcl:"iso_checksum_type,optional"`
	RawSingleISOUrl                string            `mapstructure:"iso_url" required:"true" cty:"iso_url" hcl:"iso_url,optional"`
	ISOUrls                        []string          `mapstructure:"iso_urls" cty:"iso_urls" hcl:"iso_urls,optional"`
	TargetPath                     string            `mapstructure:"iso_target_path" cty:"iso_target_path" hcl:"iso_target_path,optional"`
	TargetExtension                string            `mapstructure:"iso_target_extension" cty:"iso_target_extension" hcl:"iso_target_extension,optional"`
	FloppyFiles                    []string          `mapstructure:"floppy_files" cty:"floppy_files" hcl:"floppy_files,optional"`
	FloppyDirectories              []string          `mapstructure:"floppy_dirs" cty:"floppy_dirs" hcl:"floppy_dirs,optional"`
	FloppyLabel                    string            `mapstructure:"floppy_label" cty:"floppy_label" hcl:"floppy_label,optional"`
	RawBootGroupInterval           string            `mapstructure:"boot_keygroup_interval" cty:"boot_keygroup_interval" hcl:"boot_keygroup_interval,optional"`
	RawBootWait                    string            `mapstructure:"boot_wait" cty:"boot_wait" hcl:"boot_wait,optional"`
	BootCommand                    []string          `mapstructure:"boot_command" cty:"boot_command" hcl:"boot_command,optional"`
	BootGroupInterval              time.Duration     `cty:"boot_group_interval" hcl:"boot_group_interval,optional"`
	OutputDir                      string            `mapstructure:"output_directory" required:"false" cty:"output_directory" hcl:"output_directory,optional"`
	Type                           string            `mapstructure:"communicator" cty:"communicator" hcl:"communicator,optional"`
	PauseBeforeConnect             time.Duration     `mapstructure:"pause_before_connecting" cty:"pause_before_connecting" hcl:"pause_before_connecting,optional"`
	SSHHost                        string            `mapstructure:"ssh_host" cty:"ssh_host" hcl:"ssh_host,optional"`
	SSHPort                        int               `mapstructure:"ssh_port" cty:"ssh_port" hcl:"ssh_port,optional"`
	SSHUsername                    string            `mapstructure:"ssh_username" cty:"ssh_username" hcl:"ssh_username,optional"`
	SSHPassword                    string            `mapstructure:"ssh_password" cty:"ssh_password" hcl:"ssh_password,optional"`
	SSHKeyPairName                 string            `mapstructure:"ssh_keypair_name" cty:"ssh_keypair_name" hcl:"ssh_keypair_name,optional"`
	SSHTemporaryKeyPairName        string            `mapstructure:"temporary_key_pair_name" cty:"temporary_key_pair_name" hcl:"temporary_key_pair_name,optional"`
	SSHClearAuthorizedKeys         bool              `mapstructure:"ssh_clear_authorized_keys" cty:"ssh_clear_authorized_keys" hcl:"ssh_clear_authorized_keys,optional"`
	SSHPrivateKeyFile              string            `mapstructure:"ssh_private_key_file" cty:"ssh_private_key_file" hcl:"ssh_private_key_file,optional"`
	SSHPty                         bool              `mapstructure:"ssh_pty" cty:"ssh_pty" hcl:"ssh_pty,optional"`
	SSHTimeout                     time.Duration     `mapstructure:"ssh_timeout" cty:"ssh_timeout" hcl:"ssh_timeout,optional"`
	SSHAgentAuth                   bool              `mapstructure:"ssh_agent_auth" cty:"ssh_agent_auth" hcl:"ssh_agent_auth,optional"`
	SSHDisableAgentForwarding      bool              `mapstructure:"ssh_disable_agent_forwarding" cty:"ssh_disable_agent_forwarding" hcl:"ssh_disable_agent_forwarding,optional"`
	SSHHandshakeAttempts           int               `mapstructure:"ssh_handshake_attempts" cty:"ssh_handshake_attempts" hcl:"ssh_handshake_attempts,optional"`
	SSHBastionHost                 string            `mapstructure:"ssh_bastion_host" cty:"ssh_bastion_host" hcl:"ssh_bastion_host,optional"`
	SSHBastionPort                 int               `mapstructure:"ssh_bastion_port" cty:"ssh_bastion_port" hcl:"ssh_bastion_port,optional"`
	SSHBastionAgentAuth            bool              `mapstructure:"ssh_bastion_agent_auth" cty:"ssh_bastion_agent_auth" hcl:"ssh_bastion_agent_auth,optional"`
	SSHBastionUsername             string            `mapstructure:"ssh_bastion_username" cty:"ssh_bastion_username" hcl:"ssh_bastion_username,optional"`
	SSHBastionPassword             string            `mapstructure:"ssh_bastion_password" cty:"ssh_bastion_password" hcl:"ssh_bastion_password,optional"`
	SSHBastionPrivateKeyFile       string            `mapstructure:"ssh_bastion_private_key_file" cty:"ssh_bastion_private_key_file" hcl:"ssh_bastion_private_key_file,optional"`
	SSHFileTransferMethod          string            `mapstructure:"ssh_file_transfer_method" cty:"ssh_file_transfer_method" hcl:"ssh_file_transfer_method,optional"`
	SSHProxyHost                   string            `mapstructure:"ssh_proxy_host" cty:"ssh_proxy_host" hcl:"ssh_proxy_host,optional"`
	SSHProxyPort                   int               `mapstructure:"ssh_proxy_port" cty:"ssh_proxy_port" hcl:"ssh_proxy_port,optional"`
	SSHProxyUsername               string            `mapstructure:"ssh_proxy_username" cty:"ssh_proxy_username" hcl:"ssh_proxy_username,optional"`
	SSHProxyPassword               string            `mapstructure:"ssh_proxy_password" cty:"ssh_proxy_password" hcl:"ssh_proxy_password,optional"`
	SSHKeepAliveInterval           time.Duration     `mapstructure:"ssh_keep_alive_interval" cty:"ssh_keep_alive_interval" hcl:"ssh_keep_alive_interval,optional"`
	SSHReadWriteTimeout            time.Duration     `mapstructure:"ssh_read_write_timeout" cty:"ssh_read_write_timeout" hcl:"ssh_read_write_timeout,optional"`
	SSHRemoteTunnels               []string          `mapstructure:"ssh_remote_tunnels" cty:"ssh_remote_tunnels" hcl:"ssh_remote_tunnels,optional"`
	SSHLocalTunnels                []string          `mapstructure:"ssh_local_tunnels" cty:"ssh_local_tunnels" hcl:"ssh_local_tunnels,optional"`
	SSHPublicKey                   []byte            `cty:"ssh_public_key" hcl:"ssh_public_key,optional"`
	SSHPrivateKey                  []byte            `cty:"ssh_private_key" hcl:"ssh_private_key,optional"`
	WinRMUser                      string            `mapstructure:"winrm_username" cty:"winrm_username" hcl:"winrm_username,optional"`
	WinRMPassword                  string            `mapstructure:"winrm_password" cty:"winrm_password" hcl:"winrm_password,optional"`
	WinRMHost                      string            `mapstructure:"winrm_host" cty:"winrm_host" hcl:"winrm_host,optional"`
	WinRMPort                      int               `mapstructure:"winrm_port" cty:"winrm_port" hcl:"winrm_port,optional"`
	WinRMTimeout                   time.Duration     `mapstructure:"winrm_timeout" cty:"winrm_timeout" hcl:"winrm_timeout,optional"`
	WinRMUseSSL                    bool              `mapstructure:"winrm_use_ssl" cty:"winrm_use_ssl" hcl:"winrm_use_ssl,optional"`
	WinRMInsecure                  bool              `mapstructure:"winrm_insecure" cty:"winrm_insecure" hcl:"winrm_insecure,optional"`
	WinRMUseNTLM                   bool              `mapstructure:"winrm_use_ntlm" cty:"winrm_use_ntlm" hcl:"winrm_use_ntlm,optional"`
	ShutdownCommand                string            `mapstructure:"shutdown_command" required:"false" cty:"shutdown_command" hcl:"shutdown_command,optional"`
	RawShutdownTimeout             string            `mapstructure:"shutdown_timeout" required:"false" cty:"shutdown_timeout" hcl:"shutdown_timeout,optional"`
	RamSize                        uint              `mapstructure:"memory" required:"false" cty:"memory" hcl:"memory,optional"`
	SecondaryDvdImages             []string          `mapstructure:"secondary_iso_images" required:"false" cty:"secondary_iso_images" hcl:"secondary_iso_images,optional"`
	GuestAdditionsMode             string            `mapstructure:"guest_additions_mode" required:"false" cty:"guest_additions_mode" hcl:"guest_additions_mode,optional"`
	GuestAdditionsPath             string            `mapstructure:"guest_additions_path" required:"false" cty:"guest_additions_path" hcl:"guest_additions_path,optional"`
	CloneFromVMCXPath              string            `mapstructure:"clone_from_vmcx_path" cty:"clone_from_vmcx_path" hcl:"clone_from_vmcx_path,optional"`
	CloneFromVMName                string            `mapstructure:"clone_from_vm_name" cty:"clone_from_vm_name" hcl:"clone_from_vm_name,optional"`
	CloneFromSnapshotName          string            `mapstructure:"clone_from_snapshot_name" required:"false" cty:"clone_from_snapshot_name" hcl:"clone_from_snapshot_name,optional"`
	CloneAllSnapshots              bool              `mapstructure:"clone_all_snapshots" required:"false" cty:"clone_all_snapshots" hcl:"clone_all_snapshots,optional"`
	VMName                         string            `mapstructure:"vm_name" required:"false" cty:"vm_name" hcl:"vm_name,optional"`
	DifferencingDisk               bool              `mapstructure:"differencing_disk" required:"false" cty:"differencing_disk" hcl:"differencing_disk,optional"`
	SwitchName                     string            `mapstructure:"switch_name" required:"false" cty:"switch_name" hcl:"switch_name,optional"`
	CompareCopy                    bool              `mapstructure:"copy_in_compare" required:"false" cty:"copy_in_compare" hcl:"copy_in_compare,optional"`
	SwitchVlanId                   string            `mapstructure:"switch_vlan_id" required:"false" cty:"switch_vlan_id" hcl:"switch_vlan_id,optional"`
	MacAddress                     string            `mapstructure:"mac_address" required:"false" cty:"mac_address" hcl:"mac_address,optional"`
	VlanId                         string            `mapstructure:"vlan_id" required:"false" cty:"vlan_id" hcl:"vlan_id,optional"`
	Cpu                            uint              `mapstructure:"cpus" required:"false" cty:"cpus" hcl:"cpus,optional"`
	Generation                     uint              `mapstructure:"generation" required:"false" cty:"generation" hcl:"generation,optional"`
	EnableMacSpoofing              bool              `mapstructure:"enable_mac_spoofing" required:"false" cty:"enable_mac_spoofing" hcl:"enable_mac_spoofing,optional"`
	EnableDynamicMemory            bool              `mapstructure:"enable_dynamic_memory" required:"false" cty:"enable_dynamic_memory" hcl:"enable_dynamic_memory,optional"`
	EnableSecureBoot               bool              `mapstructure:"enable_secure_boot" required:"false" cty:"enable_secure_boot" hcl:"enable_secure_boot,optional"`
	SecureBootTemplate             string            `mapstructure:"secure_boot_template" required:"false" cty:"secure_boot_template" hcl:"secure_boot_template,optional"`
	EnableVirtualizationExtensions bool              `mapstructure:"enable_virtualization_extensions" required:"false" cty:"enable_virtualization_extensions" hcl:"enable_virtualization_extensions,optional"`
	TempPath                       string            `mapstructure:"temp_path" required:"false" cty:"temp_path" hcl:"temp_path,optional"`
	Version                        string            `mapstructure:"configuration_version" required:"false" cty:"configuration_version" hcl:"configuration_version,optional"`
	KeepRegistered                 bool              `mapstructure:"keep_registered" required:"false" cty:"keep_registered" hcl:"keep_registered,optional"`
	SkipCompaction                 bool              `mapstructure:"skip_compaction" required:"false" cty:"skip_compaction" hcl:"skip_compaction,optional"`
	SkipExport                     bool              `mapstructure:"skip_export" required:"false" cty:"skip_export" hcl:"skip_export,optional"`
	Headless                       bool              `mapstructure:"headless" required:"false" cty:"headless" hcl:"headless,optional"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{} { return new(FlatConfig) }

// HCL2Spec returns the hcldec.Spec of a Config.
// This spec is used by HCL to read the fields of Config.
func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PackerBuildName":                &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"PackerBuilderType":              &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"PackerDebug":                    &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"PackerForce":                    &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"PackerOnError":                  &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"PackerUserVars":                 &hcldec.BlockAttrsSpec{TypeName: "packer_user_variables", ElementType: cty.String, Required: false},
		"PackerSensitiveVars":            &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"HTTPDir":                        &hcldec.AttrSpec{Name: "http_directory", Type: cty.String, Required: false},
		"HTTPPortMin":                    &hcldec.AttrSpec{Name: "http_port_min", Type: cty.Number, Required: false},
		"HTTPPortMax":                    &hcldec.AttrSpec{Name: "http_port_max", Type: cty.Number, Required: false},
		"ISOChecksum":                    &hcldec.AttrSpec{Name: "iso_checksum", Type: cty.String, Required: false},
		"ISOChecksumURL":                 &hcldec.AttrSpec{Name: "iso_checksum_url", Type: cty.String, Required: false},
		"ISOChecksumType":                &hcldec.AttrSpec{Name: "iso_checksum_type", Type: cty.String, Required: false},
		"RawSingleISOUrl":                &hcldec.AttrSpec{Name: "iso_url", Type: cty.String, Required: false},
		"ISOUrls":                        &hcldec.AttrSpec{Name: "iso_urls", Type: cty.List(cty.String), Required: false},
		"TargetPath":                     &hcldec.AttrSpec{Name: "iso_target_path", Type: cty.String, Required: false},
		"TargetExtension":                &hcldec.AttrSpec{Name: "iso_target_extension", Type: cty.String, Required: false},
		"FloppyFiles":                    &hcldec.AttrSpec{Name: "floppy_files", Type: cty.List(cty.String), Required: false},
		"FloppyDirectories":              &hcldec.AttrSpec{Name: "floppy_dirs", Type: cty.List(cty.String), Required: false},
		"FloppyLabel":                    &hcldec.AttrSpec{Name: "floppy_label", Type: cty.String, Required: false},
		"RawBootGroupInterval":           &hcldec.AttrSpec{Name: "boot_keygroup_interval", Type: cty.String, Required: false},
		"RawBootWait":                    &hcldec.AttrSpec{Name: "boot_wait", Type: cty.String, Required: false},
		"BootCommand":                    &hcldec.AttrSpec{Name: "boot_command", Type: cty.List(cty.String), Required: false},
		"BootGroupInterval":              &hcldec.AttrSpec{Name: "boot_group_interval", Type: cty.String, Required: false},
		"OutputDir":                      &hcldec.AttrSpec{Name: "output_directory", Type: cty.String, Required: false},
		"Type":                           &hcldec.AttrSpec{Name: "communicator", Type: cty.String, Required: false},
		"PauseBeforeConnect":             &hcldec.AttrSpec{Name: "pause_before_connecting", Type: cty.String, Required: false},
		"SSHHost":                        &hcldec.AttrSpec{Name: "ssh_host", Type: cty.String, Required: false},
		"SSHPort":                        &hcldec.AttrSpec{Name: "ssh_port", Type: cty.Number, Required: false},
		"SSHUsername":                    &hcldec.AttrSpec{Name: "ssh_username", Type: cty.String, Required: false},
		"SSHPassword":                    &hcldec.AttrSpec{Name: "ssh_password", Type: cty.String, Required: false},
		"SSHKeyPairName":                 &hcldec.AttrSpec{Name: "ssh_keypair_name", Type: cty.String, Required: false},
		"SSHTemporaryKeyPairName":        &hcldec.AttrSpec{Name: "temporary_key_pair_name", Type: cty.String, Required: false},
		"SSHClearAuthorizedKeys":         &hcldec.AttrSpec{Name: "ssh_clear_authorized_keys", Type: cty.Bool, Required: false},
		"SSHPrivateKeyFile":              &hcldec.AttrSpec{Name: "ssh_private_key_file", Type: cty.String, Required: false},
		"SSHPty":                         &hcldec.AttrSpec{Name: "ssh_pty", Type: cty.Bool, Required: false},
		"SSHTimeout":                     &hcldec.AttrSpec{Name: "ssh_timeout", Type: cty.String, Required: false},
		"SSHAgentAuth":                   &hcldec.AttrSpec{Name: "ssh_agent_auth", Type: cty.Bool, Required: false},
		"SSHDisableAgentForwarding":      &hcldec.AttrSpec{Name: "ssh_disable_agent_forwarding", Type: cty.Bool, Required: false},
		"SSHHandshakeAttempts":           &hcldec.AttrSpec{Name: "ssh_handshake_attempts", Type: cty.Number, Required: false},
		"SSHBastionHost":                 &hcldec.AttrSpec{Name: "ssh_bastion_host", Type: cty.String, Required: false},
		"SSHBastionPort":                 &hcldec.AttrSpec{Name: "ssh_bastion_port", Type: cty.Number, Required: false},
		"SSHBastionAgentAuth":            &hcldec.AttrSpec{Name: "ssh_bastion_agent_auth", Type: cty.Bool, Required: false},
		"SSHBastionUsername":             &hcldec.AttrSpec{Name: "ssh_bastion_username", Type: cty.String, Required: false},
		"SSHBastionPassword":             &hcldec.AttrSpec{Name: "ssh_bastion_password", Type: cty.String, Required: false},
		"SSHBastionPrivateKeyFile":       &hcldec.AttrSpec{Name: "ssh_bastion_private_key_file", Type: cty.String, Required: false},
		"SSHFileTransferMethod":          &hcldec.AttrSpec{Name: "ssh_file_transfer_method", Type: cty.String, Required: false},
		"SSHProxyHost":                   &hcldec.AttrSpec{Name: "ssh_proxy_host", Type: cty.String, Required: false},
		"SSHProxyPort":                   &hcldec.AttrSpec{Name: "ssh_proxy_port", Type: cty.Number, Required: false},
		"SSHProxyUsername":               &hcldec.AttrSpec{Name: "ssh_proxy_username", Type: cty.String, Required: false},
		"SSHProxyPassword":               &hcldec.AttrSpec{Name: "ssh_proxy_password", Type: cty.String, Required: false},
		"SSHKeepAliveInterval":           &hcldec.AttrSpec{Name: "ssh_keep_alive_interval", Type: cty.String, Required: false},
		"SSHReadWriteTimeout":            &hcldec.AttrSpec{Name: "ssh_read_write_timeout", Type: cty.String, Required: false},
		"SSHRemoteTunnels":               &hcldec.AttrSpec{Name: "ssh_remote_tunnels", Type: cty.List(cty.String), Required: false},
		"SSHLocalTunnels":                &hcldec.AttrSpec{Name: "ssh_local_tunnels", Type: cty.List(cty.String), Required: false},
		"SSHPublicKey":                   &hcldec.AttrSpec{Name: "ssh_public_key", Type: cty.List(cty.Number), Required: false},
		"SSHPrivateKey":                  &hcldec.AttrSpec{Name: "ssh_private_key", Type: cty.List(cty.Number), Required: false},
		"WinRMUser":                      &hcldec.AttrSpec{Name: "winrm_username", Type: cty.String, Required: false},
		"WinRMPassword":                  &hcldec.AttrSpec{Name: "winrm_password", Type: cty.String, Required: false},
		"WinRMHost":                      &hcldec.AttrSpec{Name: "winrm_host", Type: cty.String, Required: false},
		"WinRMPort":                      &hcldec.AttrSpec{Name: "winrm_port", Type: cty.Number, Required: false},
		"WinRMTimeout":                   &hcldec.AttrSpec{Name: "winrm_timeout", Type: cty.String, Required: false},
		"WinRMUseSSL":                    &hcldec.AttrSpec{Name: "winrm_use_ssl", Type: cty.Bool, Required: false},
		"WinRMInsecure":                  &hcldec.AttrSpec{Name: "winrm_insecure", Type: cty.Bool, Required: false},
		"WinRMUseNTLM":                   &hcldec.AttrSpec{Name: "winrm_use_ntlm", Type: cty.Bool, Required: false},
		"ShutdownCommand":                &hcldec.AttrSpec{Name: "shutdown_command", Type: cty.String, Required: false},
		"RawShutdownTimeout":             &hcldec.AttrSpec{Name: "shutdown_timeout", Type: cty.String, Required: false},
		"RamSize":                        &hcldec.AttrSpec{Name: "memory", Type: cty.Number, Required: false},
		"SecondaryDvdImages":             &hcldec.AttrSpec{Name: "secondary_iso_images", Type: cty.List(cty.String), Required: false},
		"GuestAdditionsMode":             &hcldec.AttrSpec{Name: "guest_additions_mode", Type: cty.String, Required: false},
		"GuestAdditionsPath":             &hcldec.AttrSpec{Name: "guest_additions_path", Type: cty.String, Required: false},
		"CloneFromVMCXPath":              &hcldec.AttrSpec{Name: "clone_from_vmcx_path", Type: cty.String, Required: false},
		"CloneFromVMName":                &hcldec.AttrSpec{Name: "clone_from_vm_name", Type: cty.String, Required: false},
		"CloneFromSnapshotName":          &hcldec.AttrSpec{Name: "clone_from_snapshot_name", Type: cty.String, Required: false},
		"CloneAllSnapshots":              &hcldec.AttrSpec{Name: "clone_all_snapshots", Type: cty.Bool, Required: false},
		"VMName":                         &hcldec.AttrSpec{Name: "vm_name", Type: cty.String, Required: false},
		"DifferencingDisk":               &hcldec.AttrSpec{Name: "differencing_disk", Type: cty.Bool, Required: false},
		"SwitchName":                     &hcldec.AttrSpec{Name: "switch_name", Type: cty.String, Required: false},
		"CompareCopy":                    &hcldec.AttrSpec{Name: "copy_in_compare", Type: cty.Bool, Required: false},
		"SwitchVlanId":                   &hcldec.AttrSpec{Name: "switch_vlan_id", Type: cty.String, Required: false},
		"MacAddress":                     &hcldec.AttrSpec{Name: "mac_address", Type: cty.String, Required: false},
		"VlanId":                         &hcldec.AttrSpec{Name: "vlan_id", Type: cty.String, Required: false},
		"Cpu":                            &hcldec.AttrSpec{Name: "cpus", Type: cty.Number, Required: false},
		"Generation":                     &hcldec.AttrSpec{Name: "generation", Type: cty.Number, Required: false},
		"EnableMacSpoofing":              &hcldec.AttrSpec{Name: "enable_mac_spoofing", Type: cty.Bool, Required: false},
		"EnableDynamicMemory":            &hcldec.AttrSpec{Name: "enable_dynamic_memory", Type: cty.Bool, Required: false},
		"EnableSecureBoot":               &hcldec.AttrSpec{Name: "enable_secure_boot", Type: cty.Bool, Required: false},
		"SecureBootTemplate":             &hcldec.AttrSpec{Name: "secure_boot_template", Type: cty.String, Required: false},
		"EnableVirtualizationExtensions": &hcldec.AttrSpec{Name: "enable_virtualization_extensions", Type: cty.Bool, Required: false},
		"TempPath":                       &hcldec.AttrSpec{Name: "temp_path", Type: cty.String, Required: false},
		"Version":                        &hcldec.AttrSpec{Name: "configuration_version", Type: cty.String, Required: false},
		"KeepRegistered":                 &hcldec.AttrSpec{Name: "keep_registered", Type: cty.Bool, Required: false},
		"SkipCompaction":                 &hcldec.AttrSpec{Name: "skip_compaction", Type: cty.Bool, Required: false},
		"SkipExport":                     &hcldec.AttrSpec{Name: "skip_export", Type: cty.Bool, Required: false},
		"Headless":                       &hcldec.AttrSpec{Name: "headless", Type: cty.Bool, Required: false},
	}
	return s
}
