// Code generated by "mapstructure-to-hcl2 -type AwsAccessConfig"; DO NOT EDIT.
package docker

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

type FlatAwsAccessConfig struct {
	AccessKey string `mapstructure:"aws_access_key" required:"false" cty:"aws_access_key"`
	SecretKey string `mapstructure:"aws_secret_key" required:"false" cty:"aws_secret_key"`
	Token     string `mapstructure:"aws_token" required:"false" cty:"aws_token"`
	Profile   string `mapstructure:"aws_profile" required:"false" cty:"aws_profile"`
}

func (*AwsAccessConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"AccessKey": &hcldec.AttrSpec{Name: "aws_access_key", Type: cty.String, Required: false},
		"SecretKey": &hcldec.AttrSpec{Name: "aws_secret_key", Type: cty.String, Required: false},
		"Token":     &hcldec.AttrSpec{Name: "aws_token", Type: cty.String, Required: false},
		"Profile":   &hcldec.AttrSpec{Name: "aws_profile", Type: cty.String, Required: false},
	}
	return s
}

type FlatAwsAccessConfig struct {
	AccessKey string `mapstructure:"aws_access_key" required:"false" cty:"aws_access_key"`
	SecretKey string `mapstructure:"aws_secret_key" required:"false" cty:"aws_secret_key"`
	Token     string `mapstructure:"aws_token" required:"false" cty:"aws_token"`
	Profile   string `mapstructure:"aws_profile" required:"false" cty:"aws_profile"`
}

func (*AwsAccessConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"AccessKey": &hcldec.AttrSpec{Name: "aws_access_key", Type: cty.String, Required: false},
		"SecretKey": &hcldec.AttrSpec{Name: "aws_secret_key", Type: cty.String, Required: false},
		"Token":     &hcldec.AttrSpec{Name: "aws_token", Type: cty.String, Required: false},
		"Profile":   &hcldec.AttrSpec{Name: "aws_profile", Type: cty.String, Required: false},
	}
	return s
}
