// Code generated by "mapstructure-to-hcl2 -type Config"; DO NOT EDIT.
package client

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

type FlatConfig struct {
	CloudEnvironmentName string `mapstructure:"cloud_environment_name" required:"false" cty:"cloud_environment_name"`
	ClientID             string `mapstructure:"client_id" cty:"client_id"`
	ClientSecret         string `mapstructure:"client_secret" cty:"client_secret"`
	ClientCertPath       string `mapstructure:"client_cert_path" cty:"client_cert_path"`
	ClientJWT            string `mapstructure:"client_jwt" cty:"client_jwt"`
	ObjectID             string `mapstructure:"object_id" cty:"object_id"`
	TenantID             string `mapstructure:"tenant_id" required:"false" cty:"tenant_id"`
	SubscriptionID       string `mapstructure:"subscription_id" cty:"subscription_id"`
}

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"CloudEnvironmentName": &hcldec.AttrSpec{Name: "cloud_environment_name", Type: cty.String, Required: false},
		"ClientID":             &hcldec.AttrSpec{Name: "client_id", Type: cty.String, Required: false},
		"ClientSecret":         &hcldec.AttrSpec{Name: "client_secret", Type: cty.String, Required: false},
		"ClientCertPath":       &hcldec.AttrSpec{Name: "client_cert_path", Type: cty.String, Required: false},
		"ClientJWT":            &hcldec.AttrSpec{Name: "client_jwt", Type: cty.String, Required: false},
		"ObjectID":             &hcldec.AttrSpec{Name: "object_id", Type: cty.String, Required: false},
		"TenantID":             &hcldec.AttrSpec{Name: "tenant_id", Type: cty.String, Required: false},
		"SubscriptionID":       &hcldec.AttrSpec{Name: "subscription_id", Type: cty.String, Required: false},
	}
	return s
}
