// Code generated by "mapstructure-to-hcl2 -type Config"; DO NOT EDIT.
package saltmasterless

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

type FlatConfig struct {
	PackerBuildName     string            `mapstructure:"packer_build_name" cty:"packer_build_name"`
	PackerBuilderType   string            `mapstructure:"packer_builder_type" cty:"packer_builder_type"`
	PackerDebug         bool              `mapstructure:"packer_debug" cty:"packer_debug"`
	PackerForce         bool              `mapstructure:"packer_force" cty:"packer_force"`
	PackerOnError       string            `mapstructure:"packer_on_error" cty:"packer_on_error"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables"`
	SkipBootstrap       bool              `mapstructure:"skip_bootstrap" cty:"skip_bootstrap"`
	BootstrapArgs       string            `mapstructure:"bootstrap_args" cty:"bootstrap_args"`
	DisableSudo         bool              `mapstructure:"disable_sudo" cty:"disable_sudo"`
	CustomState         string            `mapstructure:"custom_state" cty:"custom_state"`
	MinionConfig        string            `mapstructure:"minion_config" cty:"minion_config"`
	GrainsFile          string            `mapstructure:"grains_file" cty:"grains_file"`
	LocalStateTree      string            `mapstructure:"local_state_tree" cty:"local_state_tree"`
	LocalPillarRoots    string            `mapstructure:"local_pillar_roots" cty:"local_pillar_roots"`
	RemoteStateTree     string            `mapstructure:"remote_state_tree" cty:"remote_state_tree"`
	RemotePillarRoots   string            `mapstructure:"remote_pillar_roots" cty:"remote_pillar_roots"`
	TempConfigDir       string            `mapstructure:"temp_config_dir" cty:"temp_config_dir"`
	NoExitOnFailure     bool              `mapstructure:"no_exit_on_failure" cty:"no_exit_on_failure"`
	LogLevel            string            `mapstructure:"log_level" cty:"log_level"`
	SaltCallArgs        string            `mapstructure:"salt_call_args" cty:"salt_call_args"`
	SaltBinDir          string            `mapstructure:"salt_bin_dir" cty:"salt_bin_dir"`
	CmdArgs             string            `cty:"cmd_args"`
	GuestOSType         string            `mapstructure:"guest_os_type" cty:"guest_os_type"`
}

func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PackerBuildName":     &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"PackerBuilderType":   &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"PackerDebug":         &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"PackerForce":         &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"PackerOnError":       &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"PackerUserVars":      &hcldec.BlockAttrsSpec{TypeName: "packer_user_variables", ElementType: cty.String, Required: false},
		"PackerSensitiveVars": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"SkipBootstrap":       &hcldec.AttrSpec{Name: "skip_bootstrap", Type: cty.Bool, Required: false},
		"BootstrapArgs":       &hcldec.AttrSpec{Name: "bootstrap_args", Type: cty.String, Required: false},
		"DisableSudo":         &hcldec.AttrSpec{Name: "disable_sudo", Type: cty.Bool, Required: false},
		"CustomState":         &hcldec.AttrSpec{Name: "custom_state", Type: cty.String, Required: false},
		"MinionConfig":        &hcldec.AttrSpec{Name: "minion_config", Type: cty.String, Required: false},
		"GrainsFile":          &hcldec.AttrSpec{Name: "grains_file", Type: cty.String, Required: false},
		"LocalStateTree":      &hcldec.AttrSpec{Name: "local_state_tree", Type: cty.String, Required: false},
		"LocalPillarRoots":    &hcldec.AttrSpec{Name: "local_pillar_roots", Type: cty.String, Required: false},
		"RemoteStateTree":     &hcldec.AttrSpec{Name: "remote_state_tree", Type: cty.String, Required: false},
		"RemotePillarRoots":   &hcldec.AttrSpec{Name: "remote_pillar_roots", Type: cty.String, Required: false},
		"TempConfigDir":       &hcldec.AttrSpec{Name: "temp_config_dir", Type: cty.String, Required: false},
		"NoExitOnFailure":     &hcldec.AttrSpec{Name: "no_exit_on_failure", Type: cty.Bool, Required: false},
		"LogLevel":            &hcldec.AttrSpec{Name: "log_level", Type: cty.String, Required: false},
		"SaltCallArgs":        &hcldec.AttrSpec{Name: "salt_call_args", Type: cty.String, Required: false},
		"SaltBinDir":          &hcldec.AttrSpec{Name: "salt_bin_dir", Type: cty.String, Required: false},
		"CmdArgs":             &hcldec.AttrSpec{Name: "cmd_args", Type: cty.String, Required: false},
		"GuestOSType":         &hcldec.AttrSpec{Name: "guest_os_type", Type: cty.String, Required: false},
	}
	return s
}
