// Code generated by "mapstructure-to-hcl2 -type Config"; DO NOT EDIT.
package shell_local

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName     string            `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name,optional"`
	PackerBuilderType   string            `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type,optional"`
	PackerDebug         bool              `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug,optional"`
	PackerForce         bool              `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force,optional"`
	PackerOnError       string            `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error,optional"`
	PackerUserVars      map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables,optional"`
	PackerSensitiveVars []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables,optional"`
	Command             string            `cty:"command" hcl:"command,optional"`
	Inline              []string          `cty:"inline" hcl:"inline,optional"`
	InlineShebang       string            `mapstructure:"inline_shebang" cty:"inline_shebang" hcl:"inline_shebang,optional"`
	OnlyOn              []string          `mapstructure:"only_on" cty:"only_on" hcl:"only_on,optional"`
	TempfileExtension   string            `mapstructure:"tempfile_extension" cty:"tempfile_extension" hcl:"tempfile_extension,optional"`
	Script              string            `cty:"script" hcl:"script,optional"`
	Scripts             []string          `cty:"scripts" hcl:"scripts,optional"`
	Vars                []string          `mapstructure:"environment_vars" cty:"environment_vars" hcl:"environment_vars,optional"`
	EnvVarFormat        string            `mapstructure:"env_var_format" cty:"env_var_format" hcl:"env_var_format,optional"`
	ExecuteCommand      []string          `mapstructure:"execute_command" cty:"execute_command" hcl:"execute_command,optional"`
	UseLinuxPathing     bool              `mapstructure:"use_linux_pathing" cty:"use_linux_pathing" hcl:"use_linux_pathing,optional"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{} { return new(FlatConfig) }

// HCL2Spec returns the hcldec.Spec of a Config.
// This spec is used by HCL to read the fields of Config.
func (*Config) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PackerBuildName":     &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"PackerBuilderType":   &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"PackerDebug":         &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"PackerForce":         &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"PackerOnError":       &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"PackerUserVars":      &hcldec.BlockAttrsSpec{TypeName: "packer_user_variables", ElementType: cty.String, Required: false},
		"PackerSensitiveVars": &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"Command":             &hcldec.AttrSpec{Name: "command", Type: cty.String, Required: false},
		"Inline":              &hcldec.AttrSpec{Name: "inline", Type: cty.List(cty.String), Required: false},
		"InlineShebang":       &hcldec.AttrSpec{Name: "inline_shebang", Type: cty.String, Required: false},
		"OnlyOn":              &hcldec.AttrSpec{Name: "only_on", Type: cty.List(cty.String), Required: false},
		"TempfileExtension":   &hcldec.AttrSpec{Name: "tempfile_extension", Type: cty.String, Required: false},
		"Script":              &hcldec.AttrSpec{Name: "script", Type: cty.String, Required: false},
		"Scripts":             &hcldec.AttrSpec{Name: "scripts", Type: cty.List(cty.String), Required: false},
		"Vars":                &hcldec.AttrSpec{Name: "environment_vars", Type: cty.List(cty.String), Required: false},
		"EnvVarFormat":        &hcldec.AttrSpec{Name: "env_var_format", Type: cty.String, Required: false},
		"ExecuteCommand":      &hcldec.AttrSpec{Name: "execute_command", Type: cty.List(cty.String), Required: false},
		"UseLinuxPathing":     &hcldec.AttrSpec{Name: "use_linux_pathing", Type: cty.Bool, Required: false},
	}
	return s
}
