// Code generated by "mapstructure-to-hcl2 -type AMIConfig"; DO NOT EDIT.
package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/hashicorp/packer/helper/config"
	"github.com/zclconf/go-cty/cty"
)

type FlatAMIConfig struct {
	AMIName                 string            `mapstructure:"ami_name" required:"true" cty:"ami_name"`
	AMIDescription          string            `mapstructure:"ami_description" required:"false" cty:"ami_description"`
	AMIVirtType             string            `mapstructure:"ami_virtualization_type" required:"false" cty:"ami_virtualization_type"`
	AMIUsers                []string          `mapstructure:"ami_users" required:"false" cty:"ami_users"`
	AMIGroups               []string          `mapstructure:"ami_groups" required:"false" cty:"ami_groups"`
	AMIProductCodes         []string          `mapstructure:"ami_product_codes" required:"false" cty:"ami_product_codes"`
	AMIRegions              []string          `mapstructure:"ami_regions" required:"false" cty:"ami_regions"`
	AMISkipRegionValidation bool              `mapstructure:"skip_region_validation" required:"false" cty:"skip_region_validation"`
	AMITags                 TagMap            `mapstructure:"tags" required:"false" cty:"tags"`
	AMIENASupport           config.Trilean    `mapstructure:"ena_support" required:"false" cty:"ena_support"`
	AMISriovNetSupport      bool              `mapstructure:"sriov_support" required:"false" cty:"sriov_support"`
	AMIForceDeregister      bool              `mapstructure:"force_deregister" required:"false" cty:"force_deregister"`
	AMIForceDeleteSnapshot  bool              `mapstructure:"force_delete_snapshot" required:"false" cty:"force_delete_snapshot"`
	AMIEncryptBootVolume    config.Trilean    `mapstructure:"encrypt_boot" required:"false" cty:"encrypt_boot"`
	AMIKmsKeyId             string            `mapstructure:"kms_key_id" required:"false" cty:"kms_key_id"`
	AMIRegionKMSKeyIDs      map[string]string `mapstructure:"region_kms_key_ids" required:"false" cty:"region_kms_key_ids"`
	AMISkipBuildRegion      bool              `mapstructure:"skip_save_build_region" cty:"skip_save_build_region"`
	SnapshotTags            TagMap            `mapstructure:"snapshot_tags" required:"false" cty:"snapshot_tags"`
	SnapshotUsers           []string          `mapstructure:"snapshot_users" required:"false" cty:"snapshot_users"`
	SnapshotGroups          []string          `mapstructure:"snapshot_groups" required:"false" cty:"snapshot_groups"`
}

func (*AMIConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"AMIName":                 &hcldec.AttrSpec{Name: "ami_name", Type: cty.String, Required: false},
		"AMIDescription":          &hcldec.AttrSpec{Name: "ami_description", Type: cty.String, Required: false},
		"AMIVirtType":             &hcldec.AttrSpec{Name: "ami_virtualization_type", Type: cty.String, Required: false},
		"AMIUsers":                &hcldec.AttrSpec{Name: "ami_users", Type: cty.List(cty.String), Required: false},
		"AMIGroups":               &hcldec.AttrSpec{Name: "ami_groups", Type: cty.List(cty.String), Required: false},
		"AMIProductCodes":         &hcldec.AttrSpec{Name: "ami_product_codes", Type: cty.List(cty.String), Required: false},
		"AMIRegions":              &hcldec.AttrSpec{Name: "ami_regions", Type: cty.List(cty.String), Required: false},
		"AMISkipRegionValidation": &hcldec.AttrSpec{Name: "skip_region_validation", Type: cty.Bool, Required: false},
		"AMITags":                 &hcldec.BlockAttrsSpec{TypeName: "TagMap", ElementType: cty.String, Required: false},
		"AMIENASupport":           &hcldec.AttrSpec{Name: "config.Trilean", Type: cty.Number, Required: false},
		"AMISriovNetSupport":      &hcldec.AttrSpec{Name: "sriov_support", Type: cty.Bool, Required: false},
		"AMIForceDeregister":      &hcldec.AttrSpec{Name: "force_deregister", Type: cty.Bool, Required: false},
		"AMIForceDeleteSnapshot":  &hcldec.AttrSpec{Name: "force_delete_snapshot", Type: cty.Bool, Required: false},
		"AMIEncryptBootVolume":    &hcldec.AttrSpec{Name: "config.Trilean", Type: cty.Number, Required: false},
		"AMIKmsKeyId":             &hcldec.AttrSpec{Name: "kms_key_id", Type: cty.String, Required: false},
		"AMIRegionKMSKeyIDs":      &hcldec.BlockAttrsSpec{TypeName: "region_kms_key_ids", ElementType: cty.String, Required: false},
		"AMISkipBuildRegion":      &hcldec.AttrSpec{Name: "skip_save_build_region", Type: cty.Bool, Required: false},
		"SnapshotTags":            &hcldec.BlockAttrsSpec{TypeName: "TagMap", ElementType: cty.String, Required: false},
		"SnapshotUsers":           &hcldec.AttrSpec{Name: "snapshot_users", Type: cty.List(cty.String), Required: false},
		"SnapshotGroups":          &hcldec.AttrSpec{Name: "snapshot_groups", Type: cty.List(cty.String), Required: false},
	}
	return s
}
