// Code generated by "mapstructure-to-hcl2 -type DriverConfig"; DO NOT EDIT.
package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

type FlatDriverConfig struct {
	FusionAppPath           string `mapstructure:"fusion_app_path" required:"false" cty:"fusion_app_path"`
	RemoteType              string `mapstructure:"remote_type" required:"false" cty:"remote_type"`
	RemoteDatastore         string `mapstructure:"remote_datastore" required:"false" cty:"remote_datastore"`
	RemoteCacheDatastore    string `mapstructure:"remote_cache_datastore" required:"false" cty:"remote_cache_datastore"`
	RemoteCacheDirectory    string `mapstructure:"remote_cache_directory" required:"false" cty:"remote_cache_directory"`
	RemoteHost              string `mapstructure:"remote_host" required:"false" cty:"remote_host"`
	RemotePort              int    `mapstructure:"remote_port" required:"false" cty:"remote_port"`
	RemoteUser              string `mapstructure:"remote_username" required:"false" cty:"remote_username"`
	RemotePassword          string `mapstructure:"remote_password" required:"false" cty:"remote_password"`
	RemotePrivateKey        string `mapstructure:"remote_private_key_file" required:"false" cty:"remote_private_key_file"`
	SkipValidateCredentials bool   `mapstructure:"skip_validate_credentials" required:"false" cty:"skip_validate_credentials"`
}

func (*DriverConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"FusionAppPath":           &hcldec.AttrSpec{Name: "fusion_app_path", Type: cty.String, Required: false},
		"RemoteType":              &hcldec.AttrSpec{Name: "remote_type", Type: cty.String, Required: false},
		"RemoteDatastore":         &hcldec.AttrSpec{Name: "remote_datastore", Type: cty.String, Required: false},
		"RemoteCacheDatastore":    &hcldec.AttrSpec{Name: "remote_cache_datastore", Type: cty.String, Required: false},
		"RemoteCacheDirectory":    &hcldec.AttrSpec{Name: "remote_cache_directory", Type: cty.String, Required: false},
		"RemoteHost":              &hcldec.AttrSpec{Name: "remote_host", Type: cty.String, Required: false},
		"RemotePort":              &hcldec.AttrSpec{Name: "remote_port", Type: cty.Number, Required: false},
		"RemoteUser":              &hcldec.AttrSpec{Name: "remote_username", Type: cty.String, Required: false},
		"RemotePassword":          &hcldec.AttrSpec{Name: "remote_password", Type: cty.String, Required: false},
		"RemotePrivateKey":        &hcldec.AttrSpec{Name: "remote_private_key_file", Type: cty.String, Required: false},
		"SkipValidateCredentials": &hcldec.AttrSpec{Name: "skip_validate_credentials", Type: cty.Bool, Required: false},
	}
	return s
}
