// Code generated by "mapstructure-to-hcl2 -type AccessConfig"; DO NOT EDIT.
package uhost

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

type FlatAccessConfig struct {
	PublicKey  string `mapstructure:"public_key" cty:"public_key"`
	PrivateKey string `mapstructure:"private_key" cty:"private_key"`
	Region     string `mapstructure:"region" cty:"region"`
	ProjectId  string `mapstructure:"project_id" cty:"project_id"`
	BaseUrl    string `mapstructure:"base_url" cty:"base_url"`
}

func (*AccessConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PublicKey":  &hcldec.AttrSpec{Name: "public_key", Type: cty.String, Required: false},
		"PrivateKey": &hcldec.AttrSpec{Name: "private_key", Type: cty.String, Required: false},
		"Region":     &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"ProjectId":  &hcldec.AttrSpec{Name: "project_id", Type: cty.String, Required: false},
		"BaseUrl":    &hcldec.AttrSpec{Name: "base_url", Type: cty.String, Required: false},
	}
	return s
}

type FlatAccessConfig struct {
	PublicKey  string `mapstructure:"public_key" cty:"public_key"`
	PrivateKey string `mapstructure:"private_key" cty:"private_key"`
	Region     string `mapstructure:"region" cty:"region"`
	ProjectId  string `mapstructure:"project_id" cty:"project_id"`
	BaseUrl    string `mapstructure:"base_url" cty:"base_url"`
}

func (*AccessConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"PublicKey":  &hcldec.AttrSpec{Name: "public_key", Type: cty.String, Required: false},
		"PrivateKey": &hcldec.AttrSpec{Name: "private_key", Type: cty.String, Required: false},
		"Region":     &hcldec.AttrSpec{Name: "region", Type: cty.String, Required: false},
		"ProjectId":  &hcldec.AttrSpec{Name: "project_id", Type: cty.String, Required: false},
		"BaseUrl":    &hcldec.AttrSpec{Name: "base_url", Type: cty.String, Required: false},
	}
	return s
}
